# Advanced Optimizer Configuration
# This configuration prioritizes student satisfaction first, then behavior/studentiality distribution,
# with advanced optimization parameters for large datasets and complex scenarios

# Scoring weights (most important part - prioritizing student satisfaction)
weights:
  student_layer:
    friends: 0.7        # Weight for placing students with their preferred friends
    dislikes: 0.3       # Weight for separating students from disliked peers
    
  class_layer:
    gender_balance: 1.0  # Weight for maintaining gender balance within classes
    
  school_layer:
    academic_balance: 0.05        # Weight for academic score distribution across classes
    behavior_balance: 0.4         # Weight for behavior rank distribution across classes
    studentiality_balance: 0.4    # Weight for studentiality rank distribution across classes
    size_balance: 0.0             # Weight for class size balance
    assistance_balance: 0.15      # Weight for assistance package distribution
    
  layers:
    student: 0.75   # Primary focus: Individual student satisfaction
    class: 0.05     # Minimal focus: Gender balance within classes
    school: 0.2     # Secondary focus: School-wide balance metrics

# Advanced optimization parameters (for large datasets and complex scenarios)
optimization:
  max_iterations: 5000           # High iteration limit for complex problems
  improvement_threshold: 0.001   # Very strict improvement threshold
  convergence_patience: 200      # High patience for complex convergence
  
  # Advanced genetic algorithm parameters
  genetic:
    population_size: 200         # Large population for complex problems
    mutation_rate: 0.2           # Higher mutation rate for complex exploration
    crossover_rate: 0.9          # Very high crossover rate
    elite_size: 40               # Large elite preservation
    tournament_size: 7           # Larger tournament size
    adaptive_mutation: true      # Enable adaptive mutation rates
    multi_objective: true        # Multi-objective optimization
    
  simulated_annealing:
    initial_temperature: 500.0   # Very high starting temperature
    cooling_rate: 0.995          # Very slow cooling
    min_temperature: 0.0001      # Very low minimum temperature
    reheat_threshold: 300        # Extended reheat threshold
    adaptive_cooling: true       # Adaptive cooling schedule
    
  local_search:
    max_neighbors: 100           # Extensive neighbor exploration
    restart_threshold: 25        # Frequent restarts for exploration
    multi_start: true            # Multiple starting points
    parallel_search: true        # Parallel search threads

# Class configuration
class_config:
  target_classes: 5
  min_class_size: 15
  max_class_size: 30
  preferred_class_size: 25
  allow_uneven_classes: true

# Normalization factors
normalization:
  academic_score_factor: 2.0
  behavior_rank_factor: 35.0
  studentiality_rank_factor: 35.0
  class_size_factor: 5.0
  assistance_count_factor: 10.0

# Validation rules
validation:
  student_id_length: 9
  max_name_length: 50
  min_academic_score: 0.0
  max_academic_score: 100.0
  valid_behavior_ranks: ['A', 'B', 'C', 'D']
  valid_boolean_values: ['true', 'false', '1', '0', 'yes', 'no', 'True', 'False', 'TRUE', 'FALSE', 'YES', 'NO'] 