# Default Scoring Configuration
# This configuration prioritizes student satisfaction first, then behavior/studentiality distribution,
# followed by assistance packages, with lower weights for other parameters

weights:
  student_layer:
    friends: 0.7        # Weight for placing students with their preferred friends
    dislikes: 0.3       # Weight for separating students from disliked peers
    
  class_layer:
    gender_balance: 1.0  # Weight for maintaining gender balance within classes
    
  school_layer:
    academic_balance: 0.05        # Weight for academic score distribution across classes
    behavior_balance: 0.4         # Weight for behavior rank distribution across classes
    studentiality_balance: 0.4    # Weight for studentiality rank distribution across classes  
    size_balance: 0.0             # Weight for class size balance
    assistance_balance: 0.15      # Weight for assistance package distribution
    school_origin_balance: 0.0    # Weight for school origin distribution balance
    
  layers:
    student: 0.75   # Primary focus: Individual student satisfaction
    class: 0.05     # Minimal focus: Gender balance within classes
    school: 0.2     # Secondary focus: School-wide balance metrics

class_config:
  target_classes: 5
  min_class_size: 15
  max_class_size: 30
  preferred_class_size: 25
  allow_uneven_classes: true

normalization:
  academic_score_factor: 2.0
  behavior_rank_factor: 35.0
  studentiality_rank_factor: 35.0
  class_size_factor: 5.0
  assistance_count_factor: 10.0
  school_origin_factor: 20.0

validation:
  student_id_length: 9
  max_name_length: 50
  min_academic_score: 0.0
  max_academic_score: 100.0
  valid_behavior_ranks: ['A', 'B', 'C', 'D']
  valid_boolean_values: ['true', 'false', '1', '0', 'yes', 'no', 'True', 'False', 'TRUE', 'FALSE', 'YES', 'NO'] 