# Default Optimizer Configuration for Meshachvetz
# Phase 2: Basic optimization with Random Swap algorithm

# Optimization algorithms and strategy
optimization:
  algorithms:
    - name: "random_swap"
      enabled: true
      parameters:
        max_iterations: 1000
        early_stop_threshold: 100
        accept_neutral_moves: false
        max_swap_attempts: 50
        
    # Future algorithms (Phase 2 Week 5+)
    - name: "genetic"
      enabled: false
      parameters:
        population_size: 50
        generations: 100
        mutation_rate: 0.1
        crossover_rate: 0.8
        elite_size: 5
        
    - name: "simulated_annealing"
      enabled: false
      parameters:
        initial_temperature: 100.0
        cooling_rate: 0.95
        min_temperature: 0.1
        cooling_schedule: "exponential"
        
    - name: "local_search"
      enabled: false
      parameters:
        max_passes: 10
        min_improvement: 0.01
        
    - name: "or_tools"
      enabled: false
      parameters:
        time_limit: 300
        
  # Multi-algorithm strategy
  strategy: "single"  # Options: "single", "sequential", "parallel", "best_of"
  default_algorithm: "random_swap"

# Constraint handling
constraints:
  # Minimum friends constraint (Phase 2 Week 4 key feature)
  minimum_friends:
    default: 1                    # Default minimum friends per student
    allow_override: true          # Can be overridden via CLI
    max_allowed: 3                # Maximum constraint value
    
  # Force constraint handling
  force_constraints:
    respect_force_class: true     # Honor force_class assignments
    respect_force_friend: true    # Honor force_friend groups
    
  # Hard constraints (must be satisfied)
  hard_constraints:
    - "force_class"
    - "force_friend"  
    - "minimum_friends"
    - "class_assignment_integrity"
    
  # Soft constraints (contribute to score but can be violated)
  soft_constraints:
    - "social_preferences"
    - "academic_balance"
    - "demographic_balance"
    - "class_size_balance"

# Initialization strategies for unassigned students
initialization:
  # Default strategy when students need assignment
  default_strategy: "constraint_aware"  # Options: random, balanced, constraint_aware, academic_balanced
  
  # Auto-initialize unassigned students during optimization
  auto_initialize: true
  
  # Target class calculation
  class_size_targets:
    min_students_per_class: 15
    max_students_per_class: 30
    preferred_students_per_class: 25
    
  # Strategy-specific settings
  strategies:
    random:
      description: "Random assignment with force constraint respect"
      
    balanced:
      description: "Balanced class sizes with round-robin assignment"
      
    constraint_aware:
      description: "Constraint-aware assignment (force_class, force_friend, preferences)"
      prioritize_force_constraints: true
      group_force_friends: true
      
    academic_balanced:
      description: "Academic score balanced distribution across classes"
      sort_by_score: true
      distribution_method: "round_robin"

# Performance settings
performance:
  max_iterations: 1000
  early_stopping: true
  early_stop_threshold: 100
  progress_reporting: true
  
# Output settings
output:
  save_optimization_history: true
  save_detailed_reports: true
  generate_comparison_reports: false

# Algorithm-specific default parameters
algorithm_defaults:
  random_swap:
    max_iterations: 1000
    early_stop_threshold: 100
    accept_neutral_moves: false
    max_swap_attempts: 50
    
  genetic:
    population_size: 50
    generations: 100
    mutation_rate: 0.1
    crossover_rate: 0.8
    elite_size: 5
    
  simulated_annealing:
    initial_temperature: 100.0
    cooling_rate: 0.95
    min_temperature: 0.1
    cooling_schedule: "exponential"
    
  local_search:
    max_passes: 10
    min_improvement: 0.01
    
  or_tools:
    time_limit: 300

# Validation settings
validation:
  validate_initial_assignment: true
  validate_intermediate_solutions: true
  validate_final_assignment: true
  fail_on_constraint_violations: true 