# Default Optimizer Configuration
# This configuration prioritizes student satisfaction first, then behavior/studentiality distribution,
# followed by assistance packages, with lower weights for other parameters

# Scoring weights (most important part)
weights:
  student_layer:
    friends: 0.95        # Weight for placing students with their preferred friends
    dislikes: 0.05       # Weight for separating students from disliked peers
    
  class_layer:
    gender_balance: 1.0  # Weight for maintaining gender balance within classes
    
  school_layer:
    academic_balance: 0.05        # Weight for academic score distribution across classes
    behavior_balance: 0.05         # Weight for behavior rank distribution across classes
    studentiality_balance: 0.05    # Weight for studentiality rank distribution across classes
    size_balance: 0.80             # Weight for class size balance
    assistance_balance: 0.5      # Weight for assistance package distribution
    
  layers:
    student: 0.80   # Primary focus: Individual student satisfaction
    class: 0.1     # Minimal focus: Gender balance within classes
    school: 0.1     # Secondary focus: School-wide balance metrics

# Optimization parameters
optimization:
  max_iterations: 1000           # Maximum number of optimization iterations
  improvement_threshold: 0.01    # Minimum improvement to continue optimization
  convergence_patience: 50       # Iterations without improvement before stopping
  
  # Algorithm-specific parameters
  genetic:
    population_size: 50          # Size of genetic algorithm population
    mutation_rate: 0.1           # Probability of mutation
    crossover_rate: 0.8          # Probability of crossover
    elite_size: 10               # Number of elite individuals to preserve
    
  simulated_annealing:
    initial_temperature: 100.0   # Starting temperature
    cooling_rate: 0.95           # Temperature reduction factor
    min_temperature: 0.01        # Minimum temperature
    
  local_search:
    max_neighbors: 30            # Maximum neighbors to explore per iteration
    restart_threshold: 150       # Iterations before restart

# Class configuration
class_config:
  target_classes: 5
  min_class_size: 35
  max_class_size: 41
  preferred_class_size: 37
  allow_uneven_classes: true

# Normalization factors
normalization:
  academic_score_factor: 2.0
  behavior_rank_factor: 35.0
  studentiality_rank_factor: 35.0
  class_size_factor: 7.0
  assistance_count_factor: 10.0

# Validation rules
validation:
  student_id_length: 9
  max_name_length: 50
  min_academic_score: 0.0
  max_academic_score: 100.0
  valid_behavior_ranks: ['A', 'B', 'C', 'D']
  valid_boolean_values: ['true', 'false', '1', '0', 'yes', 'no', 'True', 'False', 'TRUE', 'FALSE', 'YES', 'NO'] 