# Week 6 Enhanced Optimizer Configuration
# This configuration prioritizes student satisfaction first, then behavior/studentiality distribution,
# with enhanced optimization parameters for better performance

# Scoring weights (most important part - prioritizing student satisfaction)
weights:
  student_layer:
    friends: 0.7        # Weight for placing students with their preferred friends
    dislikes: 0.3       # Weight for separating students from disliked peers
    
  class_layer:
    gender_balance: 1.0  # Weight for maintaining gender balance within classes
    
  school_layer:
    academic_balance: 0.05        # Weight for academic score distribution across classes
    behavior_balance: 0.4         # Weight for behavior rank distribution across classes
    studentiality_balance: 0.4    # Weight for studentiality rank distribution across classes
    size_balance: 0.0             # Weight for class size balance
    assistance_balance: 0.15      # Weight for assistance package distribution
    
  layers:
    student: 0.75   # Primary focus: Individual student satisfaction
    class: 0.05     # Minimal focus: Gender balance within classes
    school: 0.2     # Secondary focus: School-wide balance metrics

# Enhanced optimization parameters
optimization:
  max_iterations: 2000           # Increased maximum iterations for better results
  improvement_threshold: 0.005   # Stricter improvement threshold
  convergence_patience: 100      # Increased patience for convergence
  
  # Enhanced genetic algorithm parameters
  genetic:
    population_size: 100         # Larger population for better diversity
    mutation_rate: 0.15          # Higher mutation rate for exploration
    crossover_rate: 0.85         # Higher crossover rate
    elite_size: 20               # More elite individuals preserved
    tournament_size: 5           # Tournament selection parameter
    adaptive_mutation: true      # Enable adaptive mutation rates
    
  simulated_annealing:
    initial_temperature: 200.0   # Higher starting temperature
    cooling_rate: 0.98           # Slower cooling for better exploration
    min_temperature: 0.001       # Lower minimum temperature
    reheat_threshold: 200        # Reheat after stagnation
    
  local_search:
    max_neighbors: 50            # More neighbors explored per iteration
    restart_threshold: 50        # Earlier restart for better exploration
    multi_start: true            # Multiple starting points

# Class configuration
class_config:
  target_classes: 5
  min_class_size: 15
  max_class_size: 30
  preferred_class_size: 25
  allow_uneven_classes: true

# Normalization factors
normalization:
  academic_score_factor: 2.0
  behavior_rank_factor: 35.0
  studentiality_rank_factor: 35.0
  class_size_factor: 5.0
  assistance_count_factor: 10.0

# Validation rules
validation:
  student_id_length: 9
  max_name_length: 50
  min_academic_score: 0.0
  max_academic_score: 100.0
  valid_behavior_ranks: ['A', 'B', 'C', 'D']
  valid_boolean_values: ['true', 'false', '1', '0', 'yes', 'no', 'True', 'False', 'TRUE', 'FALSE', 'YES', 'NO'] 